server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customerDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: customer-service
  output:
    ansi:
      enabled: ALWAYS
  main:
    allow-bean-definition-overriding: true


rabbitmq:
  exchange: amount_service_exchange
  order:
    queue: order_info_queue
    routing-key: order_info_key
  payment:
    queue: payment_info_queue
    routing-key: payment_info_queue


okta:
  oauth2:
    issuer: https://dev-82346525.okta.com/oauth2/default
    client-id: id
    client-secret: secret
    redirect-uri: /authorization-code/callback
    scopes: openid
    groups-claim: groups
  app:
    id: id
    role:
      customer:
        id: id