server:
  port: 8090
spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/orderDB
    username: postgres
    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
  application:
    name: order-service
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      client:
        registration:
          okta:
            clientId: id
            clientSecret: secret
            authorizationGrantType: client_credentials
            scope: data_access
        provider:
          okta:
            tokenUri: https://dev-82346525.okta.com/oauth2/default/v1/token



rabbitmq:
  exchange: amount_service_exchange
  order:
    queue: order_info_queue
    routing-key: order_info_key
  payment:
    queue: payment_info_queue
    routing-key: payment_info_queue



CUSTOMER_SERVICE_URL: http://localhost:8080/api/v1/customers


